### ISSUE TITLE
warp-point missing

### ISSUE THREAD

**Issue by EnderOmega001** [shmove/LeahsPlatinumTracker#3]
the passage between the marsh and pastoria city is missing
the passage in the fight area leadint to the battle frontier/battle park is missing
warp-point not properly aligned in the baklot mansion

**Comment by shmove** [comment]
To my knowledge, the warps related to the Great Marsh are not randomised in the newest version of PointCrow's Universal Randomiser, and will always lead to their vanilla destinations.

However, I believe the warp leading in to the Battle Frontier was added to the randomiser after I tested to see if it was affected, and I will fix this as soon as possible. Likewise the Backlot Mansion warps displaying incorrectly are also a mistake and will be fixed. Thank you for letting me know.

**Comment by shmove** [comment]
These issues have been fixed in commits https://github.com/shmove/LeahsPlatinumTracker/commit/43b55e475dc661c41d32aa1675a403500f5a29f6 and https://github.com/shmove/LeahsPlatinumTracker/commit/5b36cd0315fdafa532c555f6c1724a25c4960138 respectively.

Please note that due to an error on my part you will need to reinstall the program from the newest setup file to update to the newest version where these mistakes have been corrected. I apologise for any inconvenience this causes.
